name: Build scripts

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: build scripts
        uses: ./.github/actions/bundle
        with:
          source: ./src
          output: ./dist
      - name: Commit & Push docs to this repo
        uses: actions-js/push@v1.2
        with:
          github_token: ${{ secrets.NICK_PERSONAL_TOKEN }}