name: Generate docs

on:
  push:
    branches:
      - "master"

jobs:
  test-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: nick-mazuk/lua-docs-generator@v1.0.4
        with:
          input: './library'
          output: './docs/library'
      - name: Commit & Push docs
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}